### ISSUE TITLE
Infinite Login Loop

### ISSUE THREAD

**Issue by jonest17** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#1]
When I pressed on Hello tyler.jones@domtar.com!, pressed the view training results, and then pressed on view user details it sent me to a login screen and when I attempted to login in it puts me in an infinite loop taking me to a fresh login screen every time. This issue happens every time I attempt it. My accounts email address is tyler.jones@domtar.com.

**Comment by michaelbmorris** [comment]
The "View User Details" is intended to be for administrator use only, and as such, the button has been hidden for non-administrators.
