### ISSUE TITLE
blank screen for group b

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#12]
I answered no to both questions, then this came up with no text
![image](https://user-images.githubusercontent.com/31249115/29621523-fc57ae98-87ee-11e7-9858-09484d6dcfd7.png)

**Comment by LoriStarnes** [comment]
looks like the issue is someone created a "A" group after I created my 3. 
![image](https://user-images.githubusercontent.com/31249115/29621604-423f61da-87ef-11e7-9695-cab537ce96a0.png)

**Comment by michaelbmorris** [comment]
That is caused by the fourth group.
