### ISSUE TITLE
formatting changes not being saved

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#15]
I changed to this and save changes:
![image](https://user-images.githubusercontent.com/31249115/29630860-a2b0a2f6-880b-11e7-94e6-8e6e9de980e3.png)
 
when I go back into the slide, the changes are not saved:
![image](https://user-images.githubusercontent.com/31249115/29630890-bcc750ea-880b-11e7-8940-dd3bdfd7b33b.png)

**Comment by LoriStarnes** [comment]
forgot to mention, I'm logged in as lori (administrator)

**Comment by LoriStarnes** [comment]
I can create new slides as admin, but not make any changes to existing slides.
I have edited several only to find out that none of the changes were saved.
Is there a way to give a message - "save successful" or "save failed"

**Comment by LoriStarnes** [comment]
Logged in as owner and changes are not being saved. I cannot edit existing slides.
None of the changes are being saved.

**Comment by michaelbmorris** [comment]
Done
