### ISSUE TITLE
Preview slideshow

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#16]
Is there a way to view the slides as seen by the users while in the owner or administrator role?
Maybe a preview pane or something?
As it is, I make changes to the slides, then have to take the training and go through all the slides until I reach the one I modified just to see how it looks.

**Comment by LoriStarnes** [comment]
Dang - never mind - I just saw the "review" tab - sorry

**Comment by michaelbmorris** [comment]
"Review" has been renamed to "Preview" for clarity.
