### ISSUE TITLE
error on resubmitting answers

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#17]
Logged in as groupc and answered a few questions incorrectly.
Clicked on "click here" and then reanswered questions.
Upon submit, I received an error that I emailed you since I couldn't copy/paste the entire thing here:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--

**Comment by michaelbmorris** [comment]
Unable to replicate
