### ISSUE TITLE
categories not reordering under groups - assign categories

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#19]
categories - view all shows this:
![image](https://user-images.githubusercontent.com/31249115/29635193-471a136e-881a-11e7-817d-f8a38b4f9473.png)

groups - assign categories shows this:
![image](https://user-images.githubusercontent.com/31249115/29635200-509932bc-881a-11e7-89a9-27216679ff4b.png)

**Comment by michaelbmorris** [comment]
Done
