### ISSUE TITLE
User's role is not showing in details page

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#20]
I recall talking about this one, but not sure if it required lots of work to display their role on the details page. In this example, Mike is a supervisor:
![image](https://user-images.githubusercontent.com/31249115/29669620-0ff03182-88b2-11e7-956c-944ebf84e7b0.png)

**Comment by michaelbmorris** [comment]
Done
