### ISSUE TITLE
Click here for incorrect answer not working

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#22]
![image](https://user-images.githubusercontent.com/31249115/29675297-c2e6077a-88c2-11e7-84c1-059f8cf4c066.png)

Server Error in '/' Application.

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /KingsportMillSafetyTraining/Error

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2053.0

**Comment by michaelbmorris** [comment]
Done
