### ISSUE TITLE
numbering is not showing up

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#26]
selecting numbers on slide text box, but they are not showing in preview
![image](https://user-images.githubusercontent.com/31249115/29685247-db75eefc-88e2-11e7-9e94-6159ebe45d80.png)
![image](https://user-images.githubusercontent.com/31249115/29685256-e4ae3592-88e2-11e7-8eb1-3f0f77671b3f.png)

**Comment by michaelbmorris** [comment]
Done
