### ISSUE TITLE
wrapped text in bullets not indenting

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#27]
text longer than the screen are wrapping at the left justify instead of staying inline with the bullet indent.
Any way to correct this?
![image](https://user-images.githubusercontent.com/31249115/29686626-b893ba2c-88e7-11e7-98a4-9eb1132f7b35.png)

**Comment by michaelbmorris** [comment]
Done
