### ISSUE TITLE
some pics not showing in quiz

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#28]
![image](https://user-images.githubusercontent.com/31249115/29835086-dee2634c-8cbe-11e7-909f-13ee57796f65.png)

**Comment by LoriStarnes** [comment]
Just noticed that this is a slide without a pic, but odd showing here.

**Comment by michaelbmorris** [comment]
This is caused by having "Show Image On Quiz?" checked when there is no image. The quiz will now ensure that there is an image before attempting to render it.
