### ISSUE TITLE
quiz answer pictures too large

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#29]
Can the size of the pictures on the quiz results page be smaller?
Not quite as small as the "view all" slides icons, but maybe where 4 or 5 can show on the screen at the same time
![image](https://user-images.githubusercontent.com/31249115/29886249-76291962-8d87-11e7-8d6b-15603b8ecadd.png)

**Comment by michaelbmorris** [comment]
The maximum height has been set to 200px, which corresponds to about five lines of text. Note that this will cause the image to shrink horizontally also.
