### ISSUE TITLE
Time out for user login

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#3]
How difficult is it to have a user kicked out after 2 hours of inactivity?
More concerned about all roles other than "user" and "security" - any roles that have access to change things shouldn't be logged in indefinitely.

**Comment by michaelbmorris** [comment]
This is handled by configuration in IIS or the web.config. Please communicate with your host to change this setting.
