### ISSUE TITLE
cannot left justify bullets

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#6]
When using the bullets button, the lines indent and I cannot left justify.

When I try to use the left justify button, it removes the bullet
![image](https://user-images.githubusercontent.com/31249115/29576117-b2517154-8734-11e7-85c4-1391156f5616.png)

**Comment by michaelbmorris** [comment]
This is an editor-only display quirk and does not affect how the content is actually displayed. Changes have been made such that list items are displayed inline with bullets.
