### ISSUE TITLE
Default font changes

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#9]
Can the default fonts be changed make them a little larger? Change to:
Category = Heading 1
Slide title = Heading 2
Slide text = Heading 3
![image](https://user-images.githubusercontent.com/31249115/29614989-3bc1a6f2-87da-11e7-97ab-0e3605b6c964.png)

**Comment by LoriStarnes** [comment]
and if you can change it, will it change the existing slides?

**Comment by michaelbmorris** [comment]
Done
